services:
  # Frontend - Simple HTML/CSS/JS with nginx
  frontend:
    image: nginx:alpine
    container_name: web-agent-frontend
    ports:
      - "3080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - mcp-server
    restart: unless-stopped
    networks:
      - web-agent-network

  # Backend API (Middleware for chat service)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-agent-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - CORS_ALLOW_ORIGINS=*
      - ENVIRONMENT=development
      - DEBUG=true
      # MCP Server configuration
      - MCP_SERVER_URL=http://mcp-server:8001
      # OpenRouter configuration
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
    volumes:
      - ./backend/app:/app/app:ro
    depends_on:
      - mcp-server
    restart: unless-stopped
    networks:
      - web-agent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Server (FastMCP Python)
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: web-agent-mcp-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - MCP_SERVER_NAME=Web-Agent-MCP-Server
      - LOG_LEVEL=INFO
    volumes:
      - ./mcp-server:/app:ro
    restart: unless-stopped
    networks:
      - web-agent-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  web-agent-network:
    driver: bridge

